-- MySQL Script generated by MySQL Workbench
-- Sun Sep 25 22:51:29 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `CPF` VARCHAR(45) NULL,
  `Endereco` VARCHAR(45) NULL,
  `Clientecol` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OS` (
  `idOS` INT NOT NULL,
  `TipoServico` ENUM('M', 'R') NULL,
  `DataEntrega` DATE NULL,
  `DataEmissao` DATE NULL,
  `Status` VARCHAR(45) NULL,
  PRIMARY KEY (`idOS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Veiculo` (
  `idVeiculo` INT NOT NULL,
  `Modelo` VARCHAR(45) NULL,
  `PlacaPolicial` VARCHAR(45) NULL,
  `AnoFrabricacao` INT NULL,
  `Fabricante` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  `OS_idOS` INT NOT NULL,
  PRIMARY KEY (`idVeiculo`, `Cliente_idCliente`, `OS_idOS`),
  INDEX `fk_Veiculo_Cliente_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Veiculo_OS1_idx` (`OS_idOS` ASC) VISIBLE,
  CONSTRAINT `fk_Veiculo_Cliente`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Veiculo_OS1`
    FOREIGN KEY (`OS_idOS`)
    REFERENCES `mydb`.`OS` (`idOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orcamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orcamento` (
  `idOrcamento` INT NOT NULL,
  `ValorPeca` FLOAT NULL,
  `ValorMaodeObra` FLOAT NULL,
  `OS_idOS` INT NOT NULL,
  PRIMARY KEY (`idOrcamento`, `OS_idOS`),
  INDEX `fk_Orcamento_OS1_idx` (`OS_idOS` ASC) VISIBLE,
  CONSTRAINT `fk_Orcamento_OS1`
    FOREIGN KEY (`OS_idOS`)
    REFERENCES `mydb`.`OS` (`idOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mao_de_Obra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mao_de_Obra` (
  `idMao_de_Obra` INT NOT NULL,
  `DescricaoServico` VARCHAR(45) NULL,
  `Custo` FLOAT NULL,
  `Orcamento_idOrcamento` INT NOT NULL,
  PRIMARY KEY (`idMao_de_Obra`, `Orcamento_idOrcamento`),
  INDEX `fk_Mao_de_Obra_Orcamento1_idx` (`Orcamento_idOrcamento` ASC) VISIBLE,
  CONSTRAINT `fk_Mao_de_Obra_Orcamento1`
    FOREIGN KEY (`Orcamento_idOrcamento`)
    REFERENCES `mydb`.`Orcamento` (`idOrcamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionários`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionários` (
  `idFuncionários` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Datanascimento` VARCHAR(45) NULL,
  `Endereço` DATE NULL,
  `Matricula` VARCHAR(45) NULL,
  PRIMARY KEY (`idFuncionários`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mecanicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mecanicos` (
  `idMecanicos` INT NOT NULL,
  `Especialidade` VARCHAR(45) NULL,
  `Funcionários_idFuncionários` INT NOT NULL,
  PRIMARY KEY (`idMecanicos`, `Funcionários_idFuncionários`),
  INDEX `fk_Mecanicos_Funcionários1_idx` (`Funcionários_idFuncionários` ASC) VISIBLE,
  CONSTRAINT `fk_Mecanicos_Funcionários1`
    FOREIGN KEY (`Funcionários_idFuncionários`)
    REFERENCES `mydb`.`Funcionários` (`idFuncionários`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EquipeMecanicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EquipeMecanicos` (
  `OS_idOS` INT NOT NULL,
  `Mecanicos_idMecanicos` INT NOT NULL,
  PRIMARY KEY (`OS_idOS`, `Mecanicos_idMecanicos`),
  INDEX `fk_OS_has_Mecanicos_Mecanicos1_idx` (`Mecanicos_idMecanicos` ASC) VISIBLE,
  INDEX `fk_OS_has_Mecanicos_OS1_idx` (`OS_idOS` ASC) VISIBLE,
  CONSTRAINT `fk_OS_has_Mecanicos_OS1`
    FOREIGN KEY (`OS_idOS`)
    REFERENCES `mydb`.`OS` (`idOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OS_has_Mecanicos_Mecanicos1`
    FOREIGN KEY (`Mecanicos_idMecanicos`)
    REFERENCES `mydb`.`Mecanicos` (`idMecanicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pecas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pecas` (
  `idPecas` INT NOT NULL,
  `Descricao` VARCHAR(45) NULL,
  `Valor` FLOAT NULL,
  `Orcamento_idOrcamento` INT NOT NULL,
  PRIMARY KEY (`idPecas`, `Orcamento_idOrcamento`),
  INDEX `fk_Pecas_Orcamento1_idx` (`Orcamento_idOrcamento` ASC) VISIBLE,
  CONSTRAINT `fk_Pecas_Orcamento1`
    FOREIGN KEY (`Orcamento_idOrcamento`)
    REFERENCES `mydb`.`Orcamento` (`idOrcamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
